name: Deploy to Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check if commit is from LeetHub
        id: check_commit
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"LeetHub"* ]]; then
            echo "::set-output name=commit_is_from_leethub::true"
          else
            echo "::set-output name=commit_is_from_leethub::false"
          fi
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        if: steps.check_commit.outputs.commit_is_from_leethub == 'false'
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # .env.production 파일을 .env로 복사하여 사용
      - name: Load .env.production
        if: steps.check_commit.outputs.commit_is_from_leethub == 'false'
        run: |
          cp .env.production .env
        shell: bash

      - name: Install dependencies and Build website
        if: steps.check_commit.outputs.commit_is_from_leethub == 'false'
        run: |
          npm ci
          npm run build
        env:
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          NODE_ENV: production  # 프로덕션 환경 설정

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        if: steps.check_commit.outputs.commit_is_from_leethub == 'false'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publishto the `gh-pages` branch:
          publish_dir: build
          cname: elrdan.com               # custom domain 사용시 활성화해야 됌